import { StyleSheet } from 'react-native';
import { spacing } from '../../lib/theme';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: '#060D15',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#14283C',
    position: 'relative',
  },
  canvasWrapper: {
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#060D15',
  },
  fallbackNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  fallbackNoticeText: {
    color: '#FFB300',
    fontSize: 11,
    fontWeight: '700',
    flexShrink: 1,
  },
  operationsMapBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 44,
    marginHorizontal: spacing.md,
    marginVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1C3A55',
    backgroundColor: '#0B1B2B',
  },
  operationsMapBtnText: {
    color: '#00E5FF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },

  // ── Top Header Controls Bar ──
  topControlsBar: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    pointerEvents: 'box-none',
  },
  headerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(6, 20, 36, 0.92)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 229, 255, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  headerLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#00E676',
  },
  headerPillText: {
    color: '#00E5FF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  topActionsGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  iconActionBtn: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: 'rgba(6, 20, 36, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  iconActionBtnActive: {
    backgroundColor: '#013369',
    borderColor: '#00E5FF',
  },

  // ── Camera Presets Bar ──
  presetsBar: {
    position: 'absolute',
    top: 64,
    left: 10,
    right: 10,
    zIndex: 20,
    pointerEvents: 'box-none',
  },
  presetsScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 10,
  },
  presetPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(8, 24, 44, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    minHeight: 44,
  },
  presetPillActive: {
    backgroundColor: '#00E5FF',
    borderColor: '#00E5FF',
  },
  presetPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#CFD8DC',
  },
  presetPillTextActive: {
    color: '#001E3D',
    fontWeight: '800',
  },

  // ── Legend Bar ──
  legendBar: {
    position: 'absolute',
    bottom: 12,
    left: 10,
    zIndex: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(6, 18, 32, 0.85)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  legendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  legendText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#90A4AE',
  },

  // ── Selected Zone Overlay Card (Bottom Sheet) ──
  overlayCard: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    maxWidth: 480,
    marginHorizontal: 'auto',
    zIndex: 30,
    backgroundColor: 'rgba(6, 20, 36, 0.98)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#00E5FF',
    padding: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.8,
    shadowRadius: 18,
    elevation: 8,
    gap: 10,
  },
  overlayHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  overlayHeaderLeft: {
    flex: 1,
    gap: 2,
  },
  overlayBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  overlayCodeBadge: {
    backgroundColor: '#013369',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 229, 255, 0.4)',
  },
  overlayCodeText: {
    color: '#00E5FF',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  overlayTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    marginTop: 2,
  },
  overlayMetaText: {
    fontSize: 11,
    color: '#90A4AE',
  },
  overlayCloseBtn: {
    padding: 4,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
  },
  overlayStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  overlayStatLabel: {
    fontSize: 10,
    color: '#90A4AE',
    fontWeight: '600',
  },
  overlayStatValue: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  overlayActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  overlayOpenBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#00E5FF',
    paddingVertical: 10,
    borderRadius: 8,
  },
  overlayOpenBtnText: {
    color: '#001E3D',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
  },

  // ── Loading Skeleton State ──
  loadingContainer: {
    position: 'absolute', top: 0, right: 0, bottom: 0, left: 0,
    zIndex: 30,
    width: '100%',
    backgroundColor: '#060D15',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
  },
  loadingSpinnerRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: 'rgba(0, 229, 255, 0.15)',
    borderTopColor: '#00E5FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  loadingSub: {
    fontSize: 12,
    color: '#90A4AE',
    textAlign: 'center',
    maxWidth: 280,
  },
  loadingProgressBarTrack: {
    width: 200,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 2,
    overflow: 'hidden',
    marginTop: 4,
  },
  loadingProgressBarFill: {
    height: '100%',
    backgroundColor: '#00E5FF',
    borderRadius: 2,
  },

  // ── Error / Fallback State ──
  errorContainer: {
    width: '100%',
    flexGrow: 1,
    backgroundColor: '#081422',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
  },
  errorIconBox: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(211, 47, 47, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(211, 47, 47, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 12,
    color: '#CFD8DC',
    textAlign: 'center',
    maxWidth: 320,
    lineHeight: 18,
  },
  errorActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  errorRetryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#013369',
    borderWidth: 1,
    borderColor: '#00E5FF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    minHeight: 44,
  },
  errorRetryText: {
    color: '#00E5FF',
    fontSize: 12,
    fontWeight: '800',
  },
  errorFallbackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    minHeight: 44,
  },
  errorFallbackText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },

  // ── Accessible zone selector (non-visual route to every zone in 3D mode) ──
  zoneListBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingHorizontal: 12,
    paddingBottom: 12,
    paddingTop: 4,
  },
  zoneListChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 10,
    borderRadius: 6,
    backgroundColor: 'rgba(8, 24, 44, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  zoneListChipActive: {
    backgroundColor: '#013369',
    borderColor: '#00E5FF',
  },
  zoneListChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#B0BEC5',
  },
  zoneListChipTextActive: {
    color: '#FFFFFF',
  },
  zoneListStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
});
