CREATE ROLE venue_migrator LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD 'local-migrator-change-me';
CREATE ROLE venue_app LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD 'local-app-change-me';
GRANT CONNECT, TEMPORARY ON DATABASE venue_wrangler TO venue_migrator, venue_app;
GRANT CREATE ON SCHEMA public TO venue_migrator;
CREATE SCHEMA app_private AUTHORIZATION venue_migrator;
ALTER DEFAULT PRIVILEGES FOR ROLE venue_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO venue_app;
ALTER DEFAULT PRIVILEGES FOR ROLE venue_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO venue_app;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
