CREATE TABLE issue_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id),
  event_id uuid NOT NULL REFERENCES events(id),
  issue_id uuid NOT NULL REFERENCES issues(id),
  action text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX issue_events_tenant_event_id_idx ON issue_events (organization_id, event_id, id);

ALTER TABLE issue_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_events FORCE ROW LEVEL SECURITY;
CREATE POLICY issue_events_tenant_scope ON issue_events
  USING (organization_id = app_private.current_tenant_id())
  WITH CHECK (organization_id = app_private.current_tenant_id());
