import { Body, ConflictException, Controller, Get, Headers, Param, ParseUUIDPipe, Post, Put, Query, Req, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import type { Request } from 'express';
import { JwtIdentityGuard } from './auth';
import { ApproveStockCountDto, CancelStockTransferDto, CloseStockPurchaseOrderShortDto, CreateStockItemDto, CreateStockPurchaseOrderDto, CreateStockTransferDto, ReceiveStockPurchaseOrderDto, ReceiveStockTransferDto, RecordStockCountDto, StartStockCountDto } from './inventory.dto';
import { InventoryService } from './inventory.service';

@Controller('v1')
@UseGuards(JwtIdentityGuard)
@ApiTags('Inventory counts')
@ApiBearerAuth()
export class InventoryController {
  constructor(private readonly inventory: InventoryService) {}
  @Get('inventory/items') items(@Req() req: Request, @Query('venueId', new ParseUUIDPipe()) venueId: string, @Query('locationId') locationId?: string) { return this.inventory.listItems(req.identity, venueId, locationId); }
  @Get('admin/venues/:venueId/inventory/items') venueItems(@Req() req: Request, @Param('venueId', new ParseUUIDPipe()) venueId: string) { return this.inventory.listVenueItems(req.identity, venueId); }
  @Post('admin/inventory/items') createItem(@Req() req: Request, @Body() dto: CreateStockItemDto, @Headers('idempotency-key') key: string) { return this.inventory.createItem(req.identity, dto, this.key(key)); }
  @Get('events/:eventId/inventory/counts') counts(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string) { return this.inventory.listCounts(req.identity, eventId); }
  @Post('events/:eventId/inventory/counts') start(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Body() dto: StartStockCountDto, @Headers('idempotency-key') key: string) { return this.inventory.startCount(req.identity, eventId, dto, this.key(key)); }
  @Put('events/:eventId/inventory/counts/:countId/lines/:lineId') record(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('countId', new ParseUUIDPipe()) countId: string, @Param('lineId', new ParseUUIDPipe()) lineId: string, @Body() dto: RecordStockCountDto, @Headers('idempotency-key') key: string) { return this.inventory.recordCount(req.identity, eventId, countId, lineId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/counts/:countId/submit') submit(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('countId', new ParseUUIDPipe()) countId: string, @Headers('idempotency-key') key: string) { return this.inventory.submit(req.identity, eventId, countId, this.key(key)); }
  @Post('events/:eventId/inventory/counts/:countId/approve') approve(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('countId', new ParseUUIDPipe()) countId: string, @Body() dto: ApproveStockCountDto, @Headers('idempotency-key') key: string) { return this.inventory.approve(req.identity, eventId, countId, dto, this.key(key)); }
  @Get('events/:eventId/inventory/transfers') transfers(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string) { return this.inventory.listTransfers(req.identity, eventId); }
  @Post('events/:eventId/inventory/transfers') createTransfer(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Body() dto: CreateStockTransferDto, @Headers('idempotency-key') key: string) { return this.inventory.createTransfer(req.identity, eventId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/transfers/:transferId/dispatch') dispatchTransfer(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('transferId', new ParseUUIDPipe()) transferId: string, @Headers('idempotency-key') key: string) { return this.inventory.dispatchTransfer(req.identity, eventId, transferId, this.key(key)); }
  @Post('events/:eventId/inventory/transfers/:transferId/receive') receiveTransfer(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('transferId', new ParseUUIDPipe()) transferId: string, @Body() dto: ReceiveStockTransferDto, @Headers('idempotency-key') key: string) { return this.inventory.receiveTransfer(req.identity, eventId, transferId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/transfers/:transferId/cancel') cancelTransfer(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('transferId', new ParseUUIDPipe()) transferId: string, @Body() dto: CancelStockTransferDto, @Headers('idempotency-key') key: string) { return this.inventory.cancelTransfer(req.identity, eventId, transferId, dto, this.key(key)); }
  @Get('events/:eventId/inventory/purchase-orders') purchaseOrders(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string) { return this.inventory.listPurchaseOrders(req.identity, eventId); }
  @Post('events/:eventId/inventory/purchase-orders') createPurchaseOrder(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Body() dto: CreateStockPurchaseOrderDto, @Headers('idempotency-key') key: string) { return this.inventory.createPurchaseOrder(req.identity, eventId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/purchase-orders/:orderId/approve') approvePurchaseOrder(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('orderId', new ParseUUIDPipe()) orderId: string, @Headers('idempotency-key') key: string) { return this.inventory.approvePurchaseOrder(req.identity, eventId, orderId, this.key(key)); }
  @Post('events/:eventId/inventory/purchase-orders/:orderId/receive') receivePurchaseOrder(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('orderId', new ParseUUIDPipe()) orderId: string, @Body() dto: ReceiveStockPurchaseOrderDto, @Headers('idempotency-key') key: string) { return this.inventory.receivePurchaseOrder(req.identity, eventId, orderId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/purchase-orders/:orderId/close-short') closePurchaseOrderShort(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('orderId', new ParseUUIDPipe()) orderId: string, @Body() dto: CloseStockPurchaseOrderShortDto, @Headers('idempotency-key') key: string) { return this.inventory.closePurchaseOrderShort(req.identity, eventId, orderId, dto, this.key(key)); }
  @Post('events/:eventId/inventory/purchase-orders/:orderId/cancel') cancelPurchaseOrder(@Req() req: Request, @Param('eventId', new ParseUUIDPipe()) eventId: string, @Param('orderId', new ParseUUIDPipe()) orderId: string, @Body() dto: CancelStockTransferDto, @Headers('idempotency-key') key: string) { return this.inventory.cancelPurchaseOrder(req.identity, eventId, orderId, dto, this.key(key)); }
  private key(key?: string) { if (!key || key.length < 16 || key.length > 200) throw new ConflictException('An Idempotency-Key between 16 and 200 characters is required.'); return key; }
}
